apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- ./deploy.yaml
- ./service.yaml
images:
- name: devopsws/go-server
  newTag: 962dd6c55c9cc23e9e0d98964cd314db32de3432
